# Install AgentShell for the current Windows user. No administrator rights are required.

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$repoRoot = [IO.Path]::GetFullPath($PSScriptRoot)
$sourceRuntime = Join-Path $repoRoot 'bin\agentshell.ps1'
$sourceHelper = Join-Path $repoRoot 'shell\agentshell.ps1'
$dataHome = if (-not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_HOME)) {
    [IO.Path]::GetFullPath($env:AGENT_SHELL_HOME)
} else {
    [IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA 'AgentShell'))
}
$installRoot = if (-not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_INSTALL_ROOT)) {
    [IO.Path]::GetFullPath($env:AGENT_SHELL_INSTALL_ROOT)
} else {
    Join-Path $dataHome 'lib'
}
$binDirectory = if (-not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_BIN_DIR)) {
    [IO.Path]::GetFullPath($env:AGENT_SHELL_BIN_DIR)
} else {
    Join-Path $dataHome 'bin'
}
$helperPath = if (-not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_POWERSHELL_HELPER)) {
    [IO.Path]::GetFullPath($env:AGENT_SHELL_POWERSHELL_HELPER)
} else {
    Join-Path $dataHome 'shell\agentshell.ps1'
}
$profilePath = if (-not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_POWERSHELL_PROFILE)) {
    [IO.Path]::GetFullPath($env:AGENT_SHELL_POWERSHELL_PROFILE)
} else {
    [IO.Path]::GetFullPath($PROFILE.CurrentUserCurrentHost)
}
$installedRuntime = Join-Path $installRoot 'agentshell.ps1'
$utf8Bom = New-Object Text.UTF8Encoding($true)
$commands = @(
    'agentshell', 'agent-run', 'agent-profile',
    'agent-codex', 'agent-codexr', 'agent-codexmv',
    'agent-claude', 'agent-gemini', 'agent-copilot'
)

function Assert-AgentShellSource {
    param([string]$Path, [string]$Description)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "AgentShell installer error: missing $Description at $Path"
    }
}

function Copy-AgentShellOwnedFile {
    param([string]$Source, [string]$Destination, [string]$Signature)
    if (Test-Path -LiteralPath $Destination -PathType Leaf) {
        $existing = [IO.File]::ReadAllText($Destination)
        if (-not $existing.StartsWith($Signature, [StringComparison]::Ordinal)) {
            throw "AgentShell installer error: refusing to replace unrelated file: $Destination"
        }
    }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Destination) | Out-Null
    Copy-Item -LiteralPath $Source -Destination $Destination -Force
}

function Write-AgentShellInstallerShim {
    param([string]$CommandName)
    $escapedRuntime = $installedRuntime.Replace("'", "''")
    $escapedInvocation = $CommandName.Replace("'", "''")
    $psPath = Join-Path $binDirectory ($CommandName + '.ps1')
    $content = @"
# Generated by AgentShell. Do not edit this shim.
param([Parameter(ValueFromRemainingArguments=`$true)][object[]]`$Arguments)
& '$escapedRuntime' -InvocationName '$escapedInvocation' -ArgumentList `$Arguments
if (`$null -ne `$LASTEXITCODE) { exit `$LASTEXITCODE }
"@
    if (Test-Path -LiteralPath $psPath -PathType Leaf) {
        $existing = [IO.File]::ReadAllText($psPath)
        if (-not $existing.StartsWith('# Generated by AgentShell.')) {
            throw "AgentShell installer error: refusing to replace unrelated command: $psPath"
        }
    }
    # Windows PowerShell 5.1 requires a BOM to decode non-ASCII paths safely.
    [IO.File]::WriteAllText($psPath, $content, $utf8Bom)

    $cmdPath = Join-Path $binDirectory ($CommandName + '.cmd')
    $cmdContent = "@echo off`r`nrem Generated by AgentShell. Do not edit this shim.`r`npowershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File `"%~dp0$CommandName.ps1`" %*`r`n"
    if (Test-Path -LiteralPath $cmdPath -PathType Leaf) {
        $existingCmd = [IO.File]::ReadAllText($cmdPath)
        if ($existingCmd -notmatch '(?i)\A@echo off\r?\nrem Generated by AgentShell\.') {
            throw "AgentShell installer error: refusing to replace unrelated command: $cmdPath"
        }
    }
    [IO.File]::WriteAllText($cmdPath, $cmdContent, [Text.Encoding]::ASCII)
}

function Add-AgentShellPathFirst {
    param([string]$PathValue, [string]$Entry)
    $parts = @($PathValue -split ';' | Where-Object {
        -not [string]::IsNullOrWhiteSpace($_) -and $_.TrimEnd('\') -ine $Entry.TrimEnd('\')
    })
    return (@($Entry) + $parts) -join ';'
}

Assert-AgentShellSource $sourceRuntime 'PowerShell runtime'
Assert-AgentShellSource $sourceHelper 'PowerShell integration helper'
New-Item -ItemType Directory -Force -Path $installRoot, $binDirectory, (Split-Path -Parent $helperPath), (Split-Path -Parent $profilePath) | Out-Null
Copy-AgentShellOwnedFile $sourceRuntime $installedRuntime '# Named, account-isolated shells for Codex and other AI command-line tools.'
Copy-AgentShellOwnedFile $sourceHelper $helperPath '# PowerShell integration for AgentShell.'

foreach ($command in $commands) {
    Write-AgentShellInstallerShim $command
}

$markerBegin = '# >>> AgentShell >>>'
$markerEnd = '# <<< AgentShell <<<'
$profileText = if (Test-Path -LiteralPath $profilePath -PathType Leaf) { [IO.File]::ReadAllText($profilePath) } else { '' }
$beginCount = [regex]::Matches($profileText, '(?m)^# >>> AgentShell >>>\s*$').Count
$endCount = [regex]::Matches($profileText, '(?m)^# <<< AgentShell <<<\s*$').Count
if ($beginCount -ne $endCount -or $beginCount -gt 1) {
    throw "AgentShell installer error: malformed AgentShell marker block in $profilePath"
}
$escapedHelper = $helperPath.Replace("'", "''")
$block = @"
$markerBegin
`$agentShellHelper = '$escapedHelper'
if (Test-Path -LiteralPath `$agentShellHelper) { . `$agentShellHelper }
$markerEnd
"@
if ($beginCount -eq 0) {
    $updatedProfileText = if ([string]::IsNullOrWhiteSpace($profileText)) {
        $block + "`r`n"
    } else {
        $profileText.TrimEnd("`r", "`n") + "`r`n`r`n" + $block + "`r`n"
    }
} else {
    $markerPattern = '(?ms)^# >>> AgentShell >>>[^\r\n]*\r?\n.*?^# <<< AgentShell <<<[^\r\n]*'
    $updatedProfileText = [regex]::Replace(
        $profileText,
        $markerPattern,
        [Text.RegularExpressions.MatchEvaluator]{ param($match) $block }
    )
    if ($profileText.EndsWith("`r`n") -and -not $updatedProfileText.EndsWith("`r`n")) {
        $updatedProfileText += "`r`n"
    }
}
if ($updatedProfileText -cne $profileText) {
    if (Test-Path -LiteralPath $profilePath -PathType Leaf) {
        $backup = $profilePath + '.agentshell-backup-' + (Get-Date -Format 'yyyyMMdd-HHmmss-fff')
        Copy-Item -LiteralPath $profilePath -Destination $backup
        Write-Host "Updated $profilePath (backup: $backup)"
    } else {
        Write-Host "Created $profilePath"
    }
    [IO.File]::WriteAllText($profilePath, $updatedProfileText, $utf8Bom)
}

$env:Path = Add-AgentShellPathFirst $env:Path $binDirectory
$customInstall = -not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_HOME) -or
    -not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_INSTALL_ROOT) -or
    -not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_BIN_DIR) -or
    -not [string]::IsNullOrWhiteSpace($env:AGENT_SHELL_POWERSHELL_PROFILE)
if (-not $customInstall -or $env:AGENT_SHELL_UPDATE_USER_PATH -eq '1') {
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    [Environment]::SetEnvironmentVariable('Path', (Add-AgentShellPathFirst $userPath $binDirectory), 'User')
}

Write-Host 'AgentShell installed for Windows PowerShell.'
Write-Host "  runtime: $installedRuntime"
Write-Host "  commands: $binDirectory"
Write-Host "  profiles: $(Join-Path $dataHome 'profiles')"
Write-Host 'Reload this PowerShell window with:'
Write-Host '  . $PROFILE'
